<?php

namespace ContainerZBOgNnM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypesense_Command_CreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'typesense.command.create' shared service.
     *
     * @return \ACSEO\TypesenseBundle\Command\CreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'acseo'.\DIRECTORY_SEPARATOR.'typesense-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CreateCommand.php';

        $container->services['typesense.command.create'] = $instance = new \ACSEO\TypesenseBundle\Command\CreateCommand(($container->services['typesense.collection_manager'] ?? $container->load('getTypesense_CollectionManagerService')));

        $instance->setName('typesense:create');

        return $instance;
    }
}
