<?php

namespace ContainerFtUjEXx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypesense_AutocompleteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'typesense.autocomplete_controller' shared service.
     *
     * @return \ACSEO\TypesenseBundle\Controller\TypesenseAutocompleteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'acseo'.\DIRECTORY_SEPARATOR.'typesense-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TypesenseAutocompleteController.php';

        return $container->services['typesense.autocomplete_controller'] = new \ACSEO\TypesenseBundle\Controller\TypesenseAutocompleteController([]);
    }
}
