<?php

namespace ContainerFtUjEXx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypesense_ClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'typesense.client' shared service.
     *
     * @return \ACSEO\TypesenseBundle\Client\TypesenseClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'acseo'.\DIRECTORY_SEPARATOR.'typesense-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Client'.\DIRECTORY_SEPARATOR.'TypesenseClient.php';

        return $container->services['typesense.client'] = new \ACSEO\TypesenseBundle\Client\TypesenseClient($container->getEnv('resolve:TYPESENSE_URL'), $container->getEnv('resolve:TYPESENSE_KEY'));
    }
}
