<?php

namespace ContainerFtUjEXx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_SerializerPropertyHydratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.serializer_property_hydrator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Hydrator\NormalizerBridgePropertyHydrator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PropertyHydratorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Hydrator'.\DIRECTORY_SEPARATOR.'NormalizerBridgePropertyHydrator.php';

        return $container->privates['ux.live_component.serializer_property_hydrator'] = new \Symfony\UX\LiveComponent\Hydrator\NormalizerBridgePropertyHydrator(($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')));
    }
}
