version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artetdecor
    ports:
      - '3306:3306'
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database