<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZBOgNnM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZBOgNnM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZBOgNnM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZBOgNnM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZBOgNnM\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZBOgNnM',
    'container.build_id' => 'aa7ba95e',
    'container.build_time' => 1677010525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZBOgNnM');
